apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apr24-quarkus-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/apr24-quarkus/overlays/development
    repoURL: https://github.com/jdubrick-ai/apr24-quarkus-gitops.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: rhdh-app
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
