apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: apr24-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr24-quarkus
  name: apr24-quarkus
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
