apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: apr24-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr24-quarkus
  name: apr24-quarkus
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: apr24-quarkus
